apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kueue
spec:
  groups:
    - name: kueue-critical-alerts
      rules:
        - alert: KueuePodDown
          annotations:
            description: 'The Kueue pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not ready.'
            runbook_url: 'https://github.com/opendatahub-io/runbooks/blob/main/alerts/kueue/kueue-pod-down.md'
            summary: 'Kueue pod is down ({{ $labels.pod }})'
          expr: 'kube_pod_status_ready{pod=~"kueue-.*", condition="true"} == 0'
          for: 5m
          labels:
            severity: critical
    - name: kueue-info-alerts
      rules:
        - alert: LowClusterQueueResourceUsage
          annotations:
            description: 'The {{ $labels.resource }} resource usage in cluster queue {{ $labels.cluster_queue }} is below 20% of its nominal quota for more than 1 day.'
            runbook_url: 'https://github.com/opendatahub-io/runbooks/blob/main/alerts/kueue/low-cluster-queue-resource-usage.md'
            summary: 'Low {{ $labels.resource }} resource usage in cluster queue {{ $labels.cluster_queue }}'
          expr: 'sum(kueue_cluster_queue_resource_usage) by (cluster_queue, resource) / sum(kueue_cluster_queue_nominal_quota) by (cluster_queue, resource) < 0.2'
          for: 1d
          labels:
            severity: info
        - alert: ResourceReservationExceedsQuota
          annotations:
            description: 'Resource {{ $labels.resource }} reservation is 10 times the available quota in cluster queue {{ $labels.cluster_queue}}'
            runbook_url: 'https://github.com/opendatahub-io/runbooks/blob/main/alerts/kueue/resource-reservation-exceeds-quota.md'
            summary: 'Resource {{ $labels.resource }} reservation far exceeds the available quota in cluster queue {{ $labels.cluster_queue}}'
          expr: '(sum(kueue_cluster_queue_resource_reservation) by (resource, cluster_queue)) / 10 > (sum(kueue_cluster_queue_nominal_quota) by (resource, cluster_queue))'
          for: 10m
          labels:
            severity: info
        - alert: PendingWorkloadPods
          annotations:
            description: 'A pod {{ $labels.pod }} in the {{ $labels.namespace }} namespace has been in the pending state for more than 3 days.'
            runbook_url: 'https://github.com/opendatahub-io/runbooks/blob/main/alerts/kueue/pending-workload-pods.md'
            summary: 'Pod {{ $labels.pod }} in the {{ $labels.namespace }} namespace has been pending for more than 3 days'
          expr: '(sum by (namespace, pod) (sum_over_time(kube_pod_status_phase{phase="Pending"}[3d])) >= 3 * 24 * 60) >0'
          for: 1m
          labels:
            severity: info
