---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-fix-multi-og
  namespace: openshift-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-fix-multi-og
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  verbs:
  - list
  - delete
# - apiGroups:
#   - ''
#   resources:
#   - pods
#   verbs:
#   - list
#   - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-fix-multi-og
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-fix-multi-og
subjects:
  - kind: ServiceAccount
    name: job-fix-multi-og
    namespace: openshift-config
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-fix-multi-og-
  name: job-fix-multi-og
  namespace: openshift-config
  # annotations:
  #   argocd.argoproj.io/hook: Sync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: job-fix-multi-og
          # image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/bash
            - -c
            - /scripts/job.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: job-fix-multi-og
            defaultMode: 0755
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: job-fix-multi-og
      serviceAccountName: job-fix-multi-og
