apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/rook/rook/refs/heads/release-1.17/deploy/examples/crds.yaml
  - https://raw.githubusercontent.com/rook/rook/refs/heads/release-1.17/deploy/examples/common.yaml

patches:
- path: patch-role.yaml
- patch: |-
    - op: add
      path: /metadata/annotations/openshift.io~1display-name
      value: Rook - Ceph
    - op: add
      path: /metadata/labels
      value: {}
    - op: add
      path: /metadata/labels/pod-security.kubernetes.io~1audit
      value: privileged
    - op: add
      path: /metadata/labels/pod-security.kubernetes.io~1warn
      value: privileged
  target:
    kind: Namespace
    name: rook-ceph
