kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-ceph-system
  namespace: rook-ceph
  labels:
    app.kubernetes.io/part-of: rook-ceph-operator
    operator: rook
    storage-backend: ceph
rules:
  - verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
    apiGroups:
      - ''
    resources:
      - pods
      - configmaps
      - services
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - deletecollection
    apiGroups:
      - apps
      - extensions
    resources:
      - daemonsets
      - statefulsets
      - deployments
  - verbs:
      - delete
    apiGroups:
      - batch
    resources:
      - cronjobs
  - verbs:
      - get
      - create
      - delete
    apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - issuers
  - verbs:
      - get
      - create
    apiGroups:
      - multicluster.x-k8s.io
    resources:
      - serviceexports
  - verbs:
      - get
      - list
      - create
      - update
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
