apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../helper

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: demo-cleanup
    namespace: adhoc-admin
    files:
      - ocp-defaults-4.16.txt
      - uninstall.sh

patches:
  - path: patch-job.yaml
    target:
      kind: Job
      name: adhoc-admin-helper
