apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  source: https://github.com/redhat-na-ssa/demo-ai-gitops-catalog.git

labels:
- includeSelectors: false
  pairs:
    demo: ai-gitops-catalog

components:
- ../components/branding

resources:
  - banner-demo.yaml
