apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    component: nim

resources:
- deployment.yaml
# - pull-secret.yaml
- pvc.yaml
- route.yaml
- service.yaml
