apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../helper

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: adhoc-custom
    files:
      - 00-usage.sh

patches:
  - path: patch-job.yaml
    target:
      kind: Job
      name: adhoc-admin-helper
